name: Run

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动点击按钮构建

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/liuxunchenglxc/my_ytdlp_docker_env:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          repository: 'Brainicism/bgutil-ytdlp-pot-provider'
          path: 'bgutil-ytdlp-pot-provider'
          fetch-depth: 1
      
      - name: Deploy provider to default path
        run: |
          cd bgutil-ytdlp-pot-provider/server/
          deno install --allow-scripts=npm:canvas --frozen
          cd node_modules
          nohup deno run --allow-env --allow-net --allow-ffi=. --allow-read=. ../src/main.ts &
          cd ../../..
          # cd ../..
          # mkdir -p /github/home/
          # mv bgutil-ytdlp-pot-provider /github/home/bgutil-ytdlp-pot-provider

      - name: Run Python Script
        run: |
          python3 -u main.py --BUZZHEAVIER_ID "${{ secrets.BUZZHEAVIER_ID }}"

      - name: Delete additional files
        run: rm -f cookies.txt