name: Run

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动点击按钮构建

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/liuxunchenglxc/my_ytdlp_docker_env:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Run Python Script
        run: |
          python3 -u main.py --BUZZHEAVIER_ID "${{ secrets.BUZZHEAVIER_ID }}"

      - name: Delete additional files
        run: rm -f cookies.txt